spring:
  application:
    name: transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: testda1727@gmail.com
    password: dpdk stxp hadw gqtx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
